[build]
  command = "npm run build"
  publish = "build"

# Default cache for all pages - 1 day
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Long cache for static assets - 1 year
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Medium cache for data files - 1 day
[[headers]]
  for = "/*.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/*.gz"
  [headers.values]
    Cache-Control = "public, max-age=86400"
