// source: dictionary.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.Entry');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.Definition');
goog.require('proto.Example');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Entry = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.Entry.repeatedFields_, null);
};
goog.inherits(proto.Entry, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Entry.displayName = 'proto.Entry';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.Entry.repeatedFields_ = [5,6,8,9,10,12,13];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Entry.prototype.toObject = function(opt_includeInstance) {
  return proto.Entry.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Entry} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Entry.toObject = function(includeInstance, msg) {
  var f, obj = {
    traditional: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    simplified: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    pinyin: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    tagsList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    examplesList: jspb.Message.toObjectList(msg.getExamplesList(),
    proto.Example.toObject, includeInstance),
    percentile: (f = jspb.Message.getField(msg, 7)) == null ? undefined : f,
    containsList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f,
    partofList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f,
    relatedList: (f = jspb.Message.getRepeatedField(msg, 10)) == null ? undefined : f,
    examplesFullList: jspb.Message.toObjectList(msg.getExamplesFullList(),
    proto.Example.toObject, includeInstance),
    definitionsList: jspb.Message.toObjectList(msg.getDefinitionsList(),
    proto.Definition.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Entry}
 */
proto.Entry.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Entry;
  return proto.Entry.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Entry} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Entry}
 */
proto.Entry.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTraditional(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSimplified(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPinyin(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.addTags(value);
      break;
    case 6:
      var value = new proto.Example;
      reader.readMessage(value,proto.Example.deserializeBinaryFromReader);
      msg.addExamples(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPercentile(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.addContains(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.addPartof(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.addRelated(value);
      break;
    case 12:
      var value = new proto.Example;
      reader.readMessage(value,proto.Example.deserializeBinaryFromReader);
      msg.addExamplesFull(value);
      break;
    case 13:
      var value = new proto.Definition;
      reader.readMessage(value,proto.Definition.deserializeBinaryFromReader);
      msg.addDefinitions(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Entry.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Entry.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Entry} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Entry.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {string} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeString(
      1,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeString(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getTagsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      5,
      f
    );
  }
  f = message.getExamplesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.Example.serializeBinaryToWriter
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getContainsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      8,
      f
    );
  }
  f = message.getPartofList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      9,
      f
    );
  }
  f = message.getRelatedList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      10,
      f
    );
  }
  f = message.getExamplesFullList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      proto.Example.serializeBinaryToWriter
    );
  }
  f = message.getDefinitionsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      proto.Definition.serializeBinaryToWriter
    );
  }
};


/**
 * optional string traditional = 1;
 * @return {string}
 */
proto.Entry.prototype.getTraditional = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.setTraditional = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.clearTraditional = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Entry.prototype.hasTraditional = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional string simplified = 2;
 * @return {string}
 */
proto.Entry.prototype.getSimplified = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.setSimplified = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.clearSimplified = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Entry.prototype.hasSimplified = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string pinyin = 3;
 * @return {string}
 */
proto.Entry.prototype.getPinyin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.setPinyin = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.clearPinyin = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Entry.prototype.hasPinyin = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated string tags = 5;
 * @return {!Array<string>}
 */
proto.Entry.prototype.getTagsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.setTagsList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.addTags = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.clearTagsList = function() {
  return this.setTagsList([]);
};


/**
 * repeated Example examples = 6;
 * @return {!Array<!proto.Example>}
 */
proto.Entry.prototype.getExamplesList = function() {
  return /** @type{!Array<!proto.Example>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Example, 6));
};


/**
 * @param {!Array<!proto.Example>} value
 * @return {!proto.Entry} returns this
*/
proto.Entry.prototype.setExamplesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.Example=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Example}
 */
proto.Entry.prototype.addExamples = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.Example, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.clearExamplesList = function() {
  return this.setExamplesList([]);
};


/**
 * optional int32 percentile = 7;
 * @return {number}
 */
proto.Entry.prototype.getPercentile = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.setPercentile = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.clearPercentile = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Entry.prototype.hasPercentile = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * repeated string contains = 8;
 * @return {!Array<string>}
 */
proto.Entry.prototype.getContainsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.setContainsList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.addContains = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.clearContainsList = function() {
  return this.setContainsList([]);
};


/**
 * repeated string partof = 9;
 * @return {!Array<string>}
 */
proto.Entry.prototype.getPartofList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 9));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.setPartofList = function(value) {
  return jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.addPartof = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.clearPartofList = function() {
  return this.setPartofList([]);
};


/**
 * repeated string related = 10;
 * @return {!Array<string>}
 */
proto.Entry.prototype.getRelatedList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 10));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.setRelatedList = function(value) {
  return jspb.Message.setField(this, 10, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.addRelated = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 10, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.clearRelatedList = function() {
  return this.setRelatedList([]);
};


/**
 * repeated Example examples_full = 12;
 * @return {!Array<!proto.Example>}
 */
proto.Entry.prototype.getExamplesFullList = function() {
  return /** @type{!Array<!proto.Example>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Example, 12));
};


/**
 * @param {!Array<!proto.Example>} value
 * @return {!proto.Entry} returns this
*/
proto.Entry.prototype.setExamplesFullList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.Example=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Example}
 */
proto.Entry.prototype.addExamplesFull = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.Example, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.clearExamplesFullList = function() {
  return this.setExamplesFullList([]);
};


/**
 * repeated Definition definitions = 13;
 * @return {!Array<!proto.Definition>}
 */
proto.Entry.prototype.getDefinitionsList = function() {
  return /** @type{!Array<!proto.Definition>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.Definition, 13));
};


/**
 * @param {!Array<!proto.Definition>} value
 * @return {!proto.Entry} returns this
*/
proto.Entry.prototype.setDefinitionsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.Definition=} opt_value
 * @param {number=} opt_index
 * @return {!proto.Definition}
 */
proto.Entry.prototype.addDefinitions = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.Definition, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.Entry} returns this
 */
proto.Entry.prototype.clearDefinitionsList = function() {
  return this.setDefinitionsList([]);
};


